baseURL = 'https://followtheproecess.github.io'
languageCode = 'en'
defaultContentLanguage = "en"
title = '@FollowTheProcess'
theme = "gokarna"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "github"

[params]
  footer = "Tom Fleet"
  description = """
    Software/Backend Developer.
    Python | Go | ML
  """
  avatarURL = "/images/profile.jpg"
  avatarSize = "size-m"
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/tom-fleet-03b03280/"},
    {name = "github", url = "https://github.com/FollowTheProcess/"},
  ]
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.css" integrity="sha384-zTROYFVGOfTw7JV7KUu8udsvW2fx4lWOsCEDqhBreBwlHI4ioVRtmIvEThzJHGET" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js" integrity="sha384-GxNFqL3r9uRJQhR+47eDxuPoNE7yLftQM8LcxzgS4HT73tp970WS/wV5p8UzCOmb" crossorigin="anonymous"></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body,);"></script>
  """
  showPostsOnHomePage = "recent"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
  identifier = "github"
  url = "https://github.com/FollowTheProcess/"
  weight = 4
  # Using feather-icons
  pre = "<span data-feather='github'></span>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true